ingress:
  enabled: true
  ingressClassName: "nginx-private"
  annotations: {}
  labels: {}
  hostname: fanout.boundcorp.net
  tls:
    - hosts: []
      secretName: ""

  fanout:
  # -- Log level for server and worker
  log_level: info
  # -- Secret key used for cookie singing and unique user IDs,
  # don't change this after the first install
  secret_key: ""
  email:
    # -- SMTP Server notifications are sent from, fully optional
    host: ""
    port: 587
    # -- SMTP credentials, when left empty, not authentication will be done
    username: ""
    # -- SMTP credentials, when left empty, not authentication will be done
    password: ""
    # -- Enable either use_tls or use_ssl, they can't be enabled at the same time.
    use_tls: false
    # -- Enable either use_tls or use_ssl, they can't be enabled at the same time.
    use_ssl: false
    # -- Connection timeout
    timeout: 30
    # -- Email from address, can either be in the format "foo@bar.baz" or "authentik <foo@bar.baz>"
    from: ""
  postgresql:
    # -- set the postgresql hostname to talk to
    # if unset and .Values.postgresql.enabled == true, will generate the default
    host: 'fanout-postgresql'
    # -- postgresql Database name
    name: "fanout"
    # -- postgresql Username
    user: "fanout"
    password: ""
    port: 5432
  redis:
    # -- set the redis hostname to talk to
    host: 'fanout-redis-master'
    password: ""

env:
  APP_HOSTNAME: fanout.com

livenessProbe:
  # -- enables or disables the livenessProbe
  enabled: true
  httpGet:
    path: /healthz/
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /healthz/
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5

prometheus:
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 3s
  rules:
    create: true

postgresql:
  # -- enable the bundled bitnami postgresql chart
  enabled: true
  postgresqlUsername: "fanout"
  # postgresqlPassword: ""
  postgresqlDatabase: "fanout"
  persistence:
    enabled: true
    storageClass: "ceph-block"
