ingress:
  enabled: true
  ingressClassName: nginx-public
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/group: "business"
    external-dns.alpha.kubernetes.io/target: "ipv4.boundcorp.net"
    external-dns/is-public: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  hostname: fanout.boundcorp.net
  tls:
    - hosts: ["fanout.boundcorp.net"]
      secretName: "fanout-boundcorp-net"

env:
  APP_HOSTNAME: fanout.boundcorp.net
  SECRET_KEY: "ckxTTJRnlgJvKusqwLXL2Vxmz3bhO0uM"
  MINIO_STORAGE_MEDIA_URL: "https://fanout.boundcorp.net/assets"

livenessProbe:
  # -- enables or disables the livenessProbe
  enabled: true

readinessProbe:
  enabled: true

prometheus:
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 3s
  rules:
    create: true

postgresql:
  # -- enable the bundled bitnami postgresql chart
  enabled: true
  storageClass: "ceph-block"

minio:
  enabled: true
