# Generated by Django 3.2.14 on 2022-07-29 00:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import fanout.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaLibraryFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('path', models.CharField(max_length=1024)),
                ('file', models.FileField(blank=True, null=True, upload_to=fanout.apps.users.models.get_library_path, verbose_name='File')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medialibrary')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
    ]
