version: '2.1'
services:
  psql:
    image: sameersbn/postgresql:9.6-2
    expose: ['5432']
    #ports: ['5432:5432']

    environment:
      DB_NAME: ${CI_PROJECT_TITLE}
      DB_PASS: ${CI_PROJECT_TITLE}
      DB_USER: ${CI_PROJECT_TITLE}
    volumes:
      - /data/${CI_PROJECT_TITLE}/postgresql:/var/lib/postgresql

  minio:
    extends:
      service: minio-with-buckets
      file: build.yml
    environment:
      MINIO_ROOT_USER: 12312345
      MINIO_ROOT_PASSWORD: 12312345
      MINIO_BUCKET: "fanout-assets"
    ports: ["9000:9000", "9001:9001"]
    command: minio server /data --console-address ":9001"
    volumes:
      - /data/${CI_PROJECT_TITLE}/minio:/data

  django_shell: # This is a one-shot command runner service, for manage.py or bash, it dies immediately
    extends:
      service: ${CI_PROJECT_TITLE}-django-dev
      file: build.yml
    volumes:
      - ../:/app
      - ../.pythonrc:/root/.pythonrc
      - ../.pythonhist:/root/.pythonhist
    links:
      - psql
      - minio
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - DJANGO_SETTINGS_MODULE
      - ENV
      - SECRET_KEY=develop_key
      - DEBUG=true
      - SERVICE=django_shell
    command: "bash"
    entrypoint: []

  runserver:
    extends:
      service: ${CI_PROJECT_TITLE}-django-dev
      file: build.yml
    #command: ["bash", "/app/compose/django/uwsgi.sh"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "$DEVELOP_BACKEND_PORT:8000"
    links:
      - psql
      - minio
    volumes:
      - ../:/app
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - DJANGO_SETTINGS_MODULE
      - ENV
      - SECRET_KEY=develop_key
      - DEBUG=true
      - SERVICE=runserver
