# Generated by Django 3.2.11 on 2022-06-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('federation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='child_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='actor',
            name='child_object_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='type',
            field=models.CharField(max_length=128),
        ),
    ]
