# Generated by Django 3.2.11 on 2022-07-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0002_auto_20220623_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='icon_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='profile_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
