# Generated by Django 3.2.15 on 2022-10-04 17:40

from django.db import migrations, models

import fanout.apps.federation.models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0003_auto_20220703_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='url',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='child_content_type',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='child_object_id',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='url',
        ),
        migrations.AddField(
            model_name='activity',
            name='verb',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Add', 'Add'), ('Announce', 'Announce'), ('Arrive', 'Arrive'), ('Block', 'Block'), ('Create', 'Create'), ('Delete', 'Delete'), ('Dislike', 'Dislike'), ('Flag', 'Flag'), ('Follow', 'Follow'), ('Ignore', 'Ignore'), ('Invite', 'Invite'), ('Join', 'Join'), ('Leave', 'Leave'), ('Like', 'Like'), ('Listen', 'Listen'), ('Move', 'Move'), ('Offer', 'Offer'), ('Question', 'Question'), ('Reject', 'Reject'), ('Read', 'Read'), ('Remove', 'Remove'), ('Share', 'Share'), ('TentativeReject', 'Tentative Reject'), ('TentativeAccept', 'Tentative Accept'), ('Travel', 'Travel'), ('Undo', 'Undo'), ('Update', 'Update'), ('View', 'View')], default=('Accept', 'Accept'), max_length=32),
        ),
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.CharField(default=fanout.apps.federation.models.actor_id_generator, max_length=512, primary_key=True, serialize=False),
        ),
    ]
